version: "3.8"

services:
  app:
    container_name: academ-ads-web
    image: academ-ads-web
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000